apiVersion: v1
kind: Service
metadata:
  name: tulia-frontend
  labels:
    app: tulia
    role: ui
spec:
  type: NodePort
  selector:
    app: tulia
    role: ui
  ports:
  - port: 80
    nodePort: 30002

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tulia-frontend
  labels:
    app: tulia
    role: ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tulia
      role: ui
  template:
    metadata:
      labels:
        app: tulia
        role: ui
    spec:
      imagePullSecrets:
      - name: tuliafront
      containers:
      - name: ui
        image: tulia/frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4200