#DOCKER TO BE ADDED LATER
#Front End
trigger:
- master

pr:
- master
- Main-Dev

pool:
  vmImage: ubuntu-latest

variables: #Path to folders
  angular: '$(Build.SourcesDirectory)/Client'

stages:
- stage: Installs_Builds
  #Runs NPM Installs
  jobs:
    - job: Main
      displayName: Install_Build
      steps:
    #Install Node
      - task: NodeTool@0
        displayName: 'Install Node.js'
        inputs:
          versionSpec: '14.x'
    #Install Angular
      - task: CmdLine@2
        displayName: Install Angular
        inputs:
          script: 'npm install -g @angular/cli'
          workingDirectory: $(angular)
    #Restore
      - task: CmdLine@2
        displayName: NPM CI
        inputs:
          script: 'npm ci'
          workingDirectory: $(angular)
    #Build Angular App
      - task: AngularCLI@1
        displayName: Angular Build
        inputs:
          command: 'build'
          project: '$(angular)'
          DisableAnalytics: false