apiVersion: v1
kind: Service
metadata:
  name: tulia-backend
  labels:
    app: tulia
    role: api
spec:
  type: NodePort
  selector:
    app: tulia
    role: api
  ports:
  - port: 80
    nodePort: 30003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tulia-backend
  labels:
    app: tulia
    role: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tulia
      role: api
  template:
    metadata:
      labels:
        app: tulia
        role: api
    spec:
      imagePullSecrets:
      - name: tuliaback
      containers:
      - name: api
        image: tulia/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4200