apiVersion: v1
kind: Namespace
metadata:
  name: tulia

---
apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-dns-label-name: tulia-api
  name: azure-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: tulia
    role: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tulia-backend
  labels:
    app: tulia
    role: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tulia
      role: api
  template:
    metadata:
      labels:
        app: tulia
        role: api
    spec:
      imagePullSecrets:
      - name: tuliaback
      containers:
      - name: api
        image: tulia/backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4200